export const storeProducts = [
  {
    id: 1,
    title: "Nike Blazer Mid '77 Vintage",
    img: "img/men-shoes-1.jpg",
    price: 90,
    category: "men",
    subcategory: "shoes",
    info:
      "The Nike Blazer Mid '77 Vintage harnesses the old-school look of Nike Basketball with a vintage midsole finish, making it look like you've been saving them for years.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Nike Air Force 1 '07 Craft",
    img: "img/men-shoes-2.jpg",
    category: "men",
    subcategory: "shoes",
    price: 100,
    info:
      "The legend lives on in the Nike Air Force 1 '07 Craft—a modern take on the iconic AF-1 with new details like fresh graphics on the tongue and heel. Crisp leather, brushed suede and exposed stitching on the upper add texture and depth while the new plush liner feels soft and comfortable. Its redesigned shape returns to OG roots, adding heritage style.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Nike Zoom Fly 3",
    img: "img/men-shoes-3.jpg",
    category: "men",
    subcategory: "shoes",
    price: 100,
    info:
      "Inspired by the Vaporfly, the Nike Zoom Fly 3 gives distance runners race-day comfort and durability. The power of a carbon-fibre plate keeps you in the running mile after mile. ",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Nike React Miler",
    img: "img/men-shoes-4.jpg",
    category: "men",
    subcategory: "shoes",
    price: 110,
    info:
      "The Nike React Miler gives you trusted stability for miles with athlete-informed performance. Made for dependability on your long runs, its intuitive design offers a locked-in fit and a durable feel.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Air Jordan 1 Low",
    img: "img/men-shoes-5.jpg",
    category: "men",
    subcategory: "shoes",
    price: 120,
    info:
      "Inspired by the original that debuted in 1985, the Air Jordan 1 Low offers a clean, classic look that's familiar yet always fresh. It's made for casual mode, with an iconic design that goes with everything and never goes out of style.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Jordan Legacy 1",
    img: "img/men-shirts-1.jpg",
    category: "men",
    subcategory: "shirts",
    price: 80,
    info:
      "Got the shoes, now get in sync with the Jordan Legacy 1 Pullover Hoodie. It's made from heavyweight loopback French terry with a snow wash for a faded, lived-in look and feel.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Jordan Legacy 1",
    img: "img/men-shirts-2.jpg",
    category: "men",
    subcategory: "shirts",
    price: 100,
    info:
      "Get in sync with your sneakers in this Jordan Legacy 1 T-Shirt. It's an all-cotton crewneck with a fresh mix of classic colours and design.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Nike Sportswear",
    img: "img/men-shirts-3.jpg",
    category: "men",
    subcategory: "shirts",
    price: 90,
    info:
      "The Nike Sportswear Hoodie is made from knit French Terry to help you stay warm in colder conditions. The stitched racing stripes on the arms feature repeating Swoosh graphics and Nike block lettering for a track-inspired finish.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Nike Sportswear Air Max",
    img: "img/men-shirts-4.jpg",
    category: "men",
    subcategory: "shirts",
    price: 75,
    info:
      "The Nike Sportswear Air Max Hoodie features details inspired by the elements that made the iconic Air Max shoe famous. Smooth polyknit fabric helps keep you warm and comfy.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Nike Dri-FIT",
    img: "img/men-shirts-5.jpg",
    category: "men",
    subcategory: "shirts",
    price: 85,
    info:
      "The Nike Dri-FIT Hoodie keeps you covered before, during and after training sessions on cooler days. Soft fleece fabric holds heat in, while sweat-wicking technology helps keep you dry.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Nike Pro Flex Vent Max",
    img: "img/men-shorts-1.jpg",
    category: "men",
    subcategory: "shorts",
    price: 95,
    info:
      "Made from lightweight, stretchy fabric, the Nike Pro Flex Vent Max Shorts move with your body through your most intense workouts. An elastic, fold-over waistband lets you adjust your fit to keep the shorts in place.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "NikeCourt Flex Ace",
    img: "img/men-shorts-2.jpg",
    category: "men",
    subcategory: "shorts",
    price: 100,
    info:
      "Lightweight and stretchy, the NikeCourt Flex Ace Shorts let you move freely on the court. Thoughtful details, like subtly textured fabric and a flat-front waistband, put a classy spin on any outfit.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    title: "Jordan Dri-FIT 23 Alpha",
    img: "img/men-shorts-3.jpg",
    category: "men",
    subcategory: "shorts",
    price: 110,
    info:
      "The Jordan Dri-FIT 23 Alpha Shorts are made from sweat-wicking fabric to help keep you dry and comfortable during training sessions.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    title: "Paris Saint-Germain 2019/20 Stadium Third",
    img: "img/men-shorts-4.jpg",
    category: "men",
    subcategory: "shorts",
    price: 85,
    info:
      "The Paris Saint-Germain Stadium Third Shorts are made from breathable, sweat-wicking fabric to help keep you cool, dry and comfortable on the pitch.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    title: "Jordan Dri-FIT 23 Alpha",
    img: "img/men-shorts-5.jpg",
    category: "men",
    subcategory: "shorts",
    price: 90,
    info:
      "The Jordan Dri-FIT 23 Alpha Shorts feature sweat-wicking technology and lightweight fabric to keep you dry and comfortable, no matter how hard you train.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 16,
    title: "Nike Air Max 2090",
    img: "img/women-shoes-1.jpg",
    category: "women",
    subcategory: "shoes",
    price: 90,
    info:
      "Bring the past into the future with the Nike Air Max 2090, a bold look inspired by the DNA of the iconic Air Max 90. Brand-new Nike Air cushioning underfoot adds unparalleled comfort while transparent mesh and vibrantly coloured textiles on select colourways blend with timeless OG features for an edgy, modernised look.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 17,
    title: "Nike Air Max 90",
    img: "img/women-shoes-2.jpg",
    category: "women",
    subcategory: "shoes",
    price: 100,
    info:
      "The Nike Air Max 90 stays true to its OG roots with the iconic Waffle sole, stitched overlays and classic TPU accents. Fresh, seasonal colours give a modern look while Max Air cushioning adds comfort to your journey.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 18,
    title: "Nike React Vision",
    img: "img/women-shoes-3.jpg",
    category: "women",
    subcategory: "shoes",
    price: 110,
    info:
      "The Nike React Vision is a story of surreal comfort. Layered textures, shapes and vivid colours are combined in a design influenced by the exaggerated world of our dreams, while React foam and an ultra-plush tongue provide surreal comfort. DIMSIX on the tongue tab rises high off the collar to add just a touch of Nike's own origin story.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 19,
    title: "Nike Air Max 90",
    img: "img/women-shoes-4.jpg",
    category: "women",
    subcategory: "shoes",
    price: 95,
    info:
      "Redesigned for casual wear, the Nike Air Max 90 stays true to its '90s running roots with a rubber Waffle outsole, stitched overlays and TPU accents. Bold new colours and fresh details combine with Max Air cushioning for everyday style and comfort.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 20,
    title: "Nike Air Max Verona",
    img: "img/women-shoes-5.jpg",
    category: "women",
    subcategory: "shoes",
    price: 80,
    info:
      "With a clean look, versatile palette and easy style-ability, the Air Max Verona gives a lifted look to any woman's outfit. The synthetic and textile upper features a plush collar, flashy colours and unique stitching patterns. The Nike Air cushioning adds a modern twist.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 21,
    title: "Women's Swoosh Pullover Hoodie",
    img: "img/women-shirts-1.jpg",
    category: "women",
    subcategory: "shirts",
    price: 80,
    info:
      "The Nike Sportswear Hoodie is made from lightweight French terry in springtime hues for a comfortable layering option in unpredictable climates. A metallic Swoosh design on the chest provides a touch of shine.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 22,
    title: "Women's Ribbed Long-Sleeve Top",
    img: "img/women-shirts-2.jpg",
    category: "women",
    subcategory: "shirts",
    price: 90,
    info:
      "Inspired by tops of the '90s, the Nike Sportswear Long-Sleeve Top is made from a soft, ribbed polyester fabric. An embroidered Nike logo on the collar and patch graphic on the left wrist complete this throwback look.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 23,
    title: "Nike Dri-FIT Academy",
    img: "img/women-shirts-3.jpg",
    category: "women",
    subcategory: "shirts",
    price: 105,
    info:
      "The Nike Dri-FIT Academy Drill Top delivers warmth to your core without getting in your way. Fabric feels soft and comfortable on the inside and wicks sweat to help keep you dry. Mesh on the sides adds breathability.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 24,
    title: "Women's Jersey Tunic",
    img: "img/women-shirts-4.jpg",
    category: "women",
    subcategory: "shirts",
    price: 90,
    info:
      "The Nike Sportswear Hoodie is made from lightweight French terry in springtime hues for a comfortable layering option in unpredictable climates. A metallic Swoosh design on the chest provides a touch of shine.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 25,
    title: "Women's Short-Sleeve Top",
    img: "img/women-shirts-5.jpg",
    category: "women",
    subcategory: "shirts",
    price: 60,
    info:
      "Made from a premium cotton fabric, the Nike Sportswear Swoosh Short-Sleeve Top gives you casual comfort with modern, street-ready style.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 26,
    title: "Women's Bike Shorts",
    img: "img/women-shorts-1.jpg",
    category: "women",
    subcategory: "shorts",
    price: 70,
    info:
      "Your favourite shorts get a fresh spin in the Nike Sportswear Leg-A-See Bike Shorts. Soft jersey fabric moves with you, and a high-waisted design feels supportive.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 27,
    title: "Women's Basketball Shorts",
    img: "img/women-shorts-2.jpg",
    category: "women",
    subcategory: "shorts",
    price: 80,
    info:
      "No more sizing up then rolling down the waistband to achieve the right length. The Nike Dri-FIT Swoosh Fly Shorts are specifically designed to fit tight around the waist so they won't slip. Cut wider through the hips and thighs with an above-the-knee length, they're not too tight and not too long, but just right for ball.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 28,
    title: "NikeCourt Flex",
    img: "img/women-shorts-3.jpg",
    category: "women",
    subcategory: "shorts",
    price: 100,
    info:
      "The NikeCourt Flex Shorts are made to move with an elastic waistband and hem vents, giving you the mobility needed for fast cuts and quick hits.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 29,
    title: "Nike 10K Icon Clash",
    img: "img/women-shorts-4.jpg",
    category: "women",
    subcategory: "shorts",
    price: 75,
    info:
      "Your favourite running gear gets a vibrant upgrade with the Nike 10K Icon Clash Shorts. A speckled print at the side brings inspiration to your outdoor run.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 30,
    title: "Nike Pro",
    img: "img/women-shorts-5.jpg",
    category: "women",
    subcategory: "shorts",
    price: 45,
    info:
      "The Nike Pro Shorts are crafted from soft, sweat-wicking fabric for cool comfort. They feature a tight fit with a wide waistband for a flattering fit and feel.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 31,
    title: "Older Kids' Basketball Shoe",
    img: "img/kids-shoes-1.jpg",
    category: "kid",
    subcategory: "shoes",
    price: 45,
    info:
      "Step your game up in the Freak 2, the 2nd edition of Giannis Antetokounmpo's signature shoe. One-of-a-kind details match the MVP's on-court identity. (Hint: there's no player like him or this shoe.) These true low-tops are built to help you feel quick and in control to beat any defender, like the Freak himself.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 32,
    title: "Nike Air Force 1 LV8 2",
    img: "img/kids-shoes-2.jpg",
    category: "kid",
    subcategory: "shoes",
    price: 75,
    info:
      "The Nike Air Force 1 LV8 2 keeps the party going with new colours, more Swooshes and a design inspired by festivals. This '82 legend still has the feel you know and love, so who's ready for a good time?",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 33,
    title: "Nike Blazer Mid",
    img: "img/kids-shoes-3.jpg",
    category: "kid",
    subcategory: "shoes",
    price: 100,
    info:
      "Flexible, durable and iconic—what more do you need? The Nike Blazer Mid re-imagines our '70s hoops classic into everyday mid-top kicks made kid-friendly.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 34,
    title: "Nike Blazer Low",
    img: "img/kids-shoes-4.jpg",
    category: "kid",
    subcategory: "shoes",
    price: 90,
    info:
      "Flexible, durable and iconic—what more do you need? The Nike Blazer Low re-imagines our '70s hoops classic into an everyday shoe made kid-friendly.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 35,
    title: "Nike Blazer Low Pop",
    img: "img/kids-shoes-5.jpg",
    category: "kid",
    subcategory: "shoes",
    price: 45,
    info:
      "Inspired by classic Nike looks from the '70s, Nike Blazer Low Pop steps out on a solid foundation of Nike heritage and vintage hoops fandom. Peep the popsicle on the sockliner before you pull them on, then pop out in style.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 36,
    title: "Older Kids' (Boys') Full-Zip Hoodie",
    img: "img/kids-shirts-1.jpg",
    category: "kid",
    subcategory: "shirts",
    price: 70,
    info:
      "When it's grab-and-go time, reach for the Nike Sportswear Swoosh Hoodie. This classic full-zip is soft, cosy and warm. Plus, it has a stripe down each sleeve with mini Swoosh designs. How many can you spot?",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 37,
    title: "Nike Sportswear Swoosh",
    img: "img/kids-shirts-2.jpg",
    category: "kid",
    subcategory: "shirts",
    price: 65,
    info:
      "Can you count the Swoosh designs? Taping at the shoulders of the Nike Sportswear Swoosh T-Shirt adds a playful detail to a comfortable classic.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 38,
    title: "Older Kids' (Boys') T-Shirt",
    img: "img/kids-shirts-3.jpg",
    category: "kid",
    subcategory: "shirts",
    price: 70,
    info:
      "The Nike Sportswear T-Shirt shows love to Nike's iconic Windrunner jacket with chevron design lines on top of your classic tee.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 39,
    title: "Older Kids' (Boys') Training Top",
    img: "img/kids-shirts-4.jpg",
    category: "kid",
    subcategory: "shirts",
    price: 85,
    info:
      "The Nike Instacool Top is all about keeping cool and comfy with super breathable fabric. When your body heats up, watch the Swoosh on the chest change colour. Plus, it has Dri-FIT Technology so you can stay dry when the pace picks up. This product is made from at least 50% recycled polyester.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 40,
    title: "Older Kids' Pullover Hoodie",
    img: "img/kids-shirts-5.jpg",
    category: "kid",
    subcategory: "shirts",
    price: 100,
    info:
      "Wear it alone or as a layer for all of your cool weather workouts. The Nike Sportswear Pullover Hoodie is made from warm fleece that feels extra soft on the inside.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 41,
    title: "Older Kids' (Girls') Shorts",
    img: "img/kids-shorts-1.jpg",
    category: "kid",
    subcategory: "shorts",
    price: 30,
    info:
      "It's all about classic comfort in the Nike Air Shorts. Soft fabric plus a stretchy waistband is everything you need for all-day play.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 42,
    title: "Older Kids' (Girls') Running Shorts",
    img: "img/kids-shorts-2.jpg",
    category: "kid",
    subcategory: "shorts",
    price: 80,
    info:
      "Nike Dry Girls' Running Shorts provide sweat-wicking comfort for a variety of activities. Nike Dry fabric helps you stay dry while a unique pocket allows storage when you're on the move. This product is made from 100%-recycled polyester fabric.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 43,
    title: "Nike Dri-FIT Tempo",
    img: "img/kids-shorts-3.jpg",
    category: "kid",
    subcategory: "shorts",
    price: 50,
    info:
      "The Nike Dri-FIT Tempo Shorts are all about keeping you cool, dry and comfortable while you're racing around. The lightweight design has mesh on the sides for a breezy feel. Built-in briefs give you extra coverage.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 44,
    title: "Nike Sportswear",
    img: "img/kids-shorts-4.jpg",
    category: "kid",
    subcategory: "shorts",
    price: 60,
    info:
      "The Nike Sportswear Shorts have a lightweight design with an elastic waistband for all-day comfort.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 45,
    title: "Older Kids' (Girls')' Training Shorts",
    img: "img/kids-shorts-5.jpg",
    category: "kid",
    subcategory: "shorts",
    price: 70,
    info:
      "Nike Dri-FIT Trophy Shorts combine a classic athletic look with fabric that pulls sweat away from the skin for cool, dry comfort while you're on the move.",
    inCart: false,
    count: 0,
    total: 0,
  },
];
